export const users = [
  { email: "admin@admin.com", role: "admin", password: "Admin123!" },
  { email: "manager@manager.com", role: "manager", password: "Manager123!" },
  { email: "user@user.com", role: "user", password: "User123!" },
];

export const groups = [
  { name: "Monitors", type: "Hardware" },
  { name: "Laptops", type: "Hardware" },
  { name: "Phones", type: "Hardware" },
  { name: "Accessories", type: "Peripheral" },
  { name: "Printers", type: "Office" },
];

export const products = [
  {
    title: "MacBook Pro",
    type: "Laptop",
    serialNumber: "MBP-001",
    isNew: true,
    photo: "",
    specification: "M1 Max, 32GB RAM, 1TB SSD",
    guaranteeStart: new Date().toISOString(),
    guaranteeEnd: new Date(
      new Date().setFullYear(new Date().getFullYear() + 1)
    ).toISOString(),
    priceUSD: 2500,
    priceUAH: 95000,
    defaultCurrency: "USD",
    groupName: "Laptops",
  },
  {
    title: "MacBook Air",
    type: "Laptop",
    serialNumber: "MBA-001",
    isNew: true,
    photo: "",
    specification: "M2, 16GB RAM, 512GB SSD",
    guaranteeStart: new Date().toISOString(),
    guaranteeEnd: new Date(
      new Date().setFullYear(new Date().getFullYear() + 1)
    ).toISOString(),
    priceUSD: 1800,
    priceUAH: 68000,
    defaultCurrency: "USD",
    groupName: "Laptops",
  },
  {
    title: "Dell Monitor",
    type: "Monitor",
    serialNumber: "DELL-1080P",
    isNew: true,
    photo: "",
    specification: '27", IPS, 1080p',
    guaranteeStart: new Date().toISOString(),
    guaranteeEnd: new Date(
      new Date().setFullYear(new Date().getFullYear() + 1)
    ).toISOString(),
    priceUSD: 300,
    priceUAH: 11000,
    defaultCurrency: "UAH",
    groupName: "Monitors",
  },
  {
    title: "LG UltraFine",
    type: "Monitor",
    serialNumber: "LG-UF-4K",
    isNew: true,
    photo: "",
    specification: '32", 4K, Thunderbolt 3',
    guaranteeStart: new Date().toISOString(),
    guaranteeEnd: new Date(
      new Date().setFullYear(new Date().getFullYear() + 2)
    ).toISOString(),
    priceUSD: 650,
    priceUAH: 23000,
    defaultCurrency: "USD",
    groupName: "Monitors",
  },
  {
    title: "iPhone 14 Pro",
    type: "Phone",
    serialNumber: "IPH14PRO-001",
    isNew: true,
    photo: "",
    specification: "256GB, Deep Purple",
    guaranteeStart: new Date().toISOString(),
    guaranteeEnd: new Date(
      new Date().setFullYear(new Date().getFullYear() + 1)
    ).toISOString(),
    priceUSD: 1300,
    priceUAH: 50000,
    defaultCurrency: "USD",
    groupName: "Phones",
  },
  {
    title: "Samsung Galaxy S23",
    type: "Phone",
    serialNumber: "SGS23-001",
    isNew: true,
    photo: "",
    specification: "256GB, Phantom Black",
    guaranteeStart: new Date().toISOString(),
    guaranteeEnd: new Date(
      new Date().setFullYear(new Date().getFullYear() + 1)
    ).toISOString(),
    priceUSD: 1000,
    priceUAH: 40000,
    defaultCurrency: "UAH",
    groupName: "Phones",
  },
  {
    title: "Logitech MX Master 3S",
    type: "Accessory",
    serialNumber: "LOGI-MX3S",
    isNew: true,
    photo: "",
    specification: "Wireless Mouse",
    guaranteeStart: new Date().toISOString(),
    guaranteeEnd: new Date(
      new Date().setFullYear(new Date().getFullYear() + 2)
    ).toISOString(),
    priceUSD: 120,
    priceUAH: 4600,
    defaultCurrency: "UAH",
    groupName: "Accessories",
  },
  {
    title: "Apple Magic Keyboard",
    type: "Accessory",
    serialNumber: "MAGKEY-001",
    isNew: true,
    photo: "",
    specification: "Wireless, Touch ID",
    guaranteeStart: new Date().toISOString(),
    guaranteeEnd: new Date(
      new Date().setFullYear(new Date().getFullYear() + 2)
    ).toISOString(),
    priceUSD: 150,
    priceUAH: 5700,
    defaultCurrency: "USD",
    groupName: "Accessories",
  },
  {
    title: "HP LaserJet Pro",
    type: "Printer",
    serialNumber: "HPLJ-001",
    isNew: true,
    photo: "",
    specification: "Mono Laser, Wi-Fi",
    guaranteeStart: new Date().toISOString(),
    guaranteeEnd: new Date(
      new Date().setFullYear(new Date().getFullYear() + 2)
    ).toISOString(),
    priceUSD: 280,
    priceUAH: 10500,
    defaultCurrency: "UAH",
    groupName: "Printers",
  },
  {
    title: "Canon PIXMA",
    type: "Printer",
    serialNumber: "PIXMA-G2020",
    isNew: true,
    photo: "",
    specification: "Color Inkjet, A4",
    guaranteeStart: new Date().toISOString(),
    guaranteeEnd: new Date(
      new Date().setFullYear(new Date().getFullYear() + 2)
    ).toISOString(),
    priceUSD: 200,
    priceUAH: 7500,
    defaultCurrency: "USD",
    groupName: "Printers",
  },
  {
    title: "Asus ZenBook 14",
    type: "Laptop",
    serialNumber: "ASUS-ZB14",
    isNew: false,
    photo: "",
    specification: "i7, 16GB RAM, 512GB SSD",
    guaranteeStart: "2023-04-01T00:00:00.000Z",
    guaranteeEnd: "2025-04-01T00:00:00.000Z",
    priceUSD: 1400,
    priceUAH: 53000,
    defaultCurrency: "UAH",
    groupName: "Laptops",
  },
  {
    title: "ThinkPad X1 Carbon",
    type: "Laptop",
    serialNumber: "TP-X1C",
    isNew: true,
    photo: "",
    specification: "i7, 32GB RAM, 1TB SSD",
    guaranteeStart: "2024-01-01T00:00:00.000Z",
    guaranteeEnd: "2026-01-01T00:00:00.000Z",
    priceUSD: 2100,
    priceUAH: 82000,
    defaultCurrency: "USD",
    groupName: "Laptops",
  },
  {
    title: "BenQ PD3200U",
    type: "Monitor",
    serialNumber: "BENQ-32U",
    isNew: true,
    photo: "",
    specification: '32", 4K UHD, 60Hz',
    guaranteeStart: "2023-12-01T00:00:00.000Z",
    guaranteeEnd: "2025-12-01T00:00:00.000Z",
    priceUSD: 700,
    priceUAH: 26000,
    defaultCurrency: "USD",
    groupName: "Monitors",
  },
  {
    title: "Samsung Smart Monitor M8",
    type: "Monitor",
    serialNumber: "SSM-M8",
    isNew: true,
    photo: "",
    specification: '32", UHD, Smart OS',
    guaranteeStart: "2024-02-10T00:00:00.000Z",
    guaranteeEnd: "2026-02-10T00:00:00.000Z",
    priceUSD: 500,
    priceUAH: 19500,
    defaultCurrency: "UAH",
    groupName: "Monitors",
  },
  {
    title: "Google Pixel 7 Pro",
    type: "Phone",
    serialNumber: "PIXEL-7P",
    isNew: true,
    photo: "",
    specification: "128GB, Snow",
    guaranteeStart: "2023-08-01T00:00:00.000Z",
    guaranteeEnd: "2025-08-01T00:00:00.000Z",
    priceUSD: 900,
    priceUAH: 35000,
    defaultCurrency: "USD",
    groupName: "Phones",
  },
  {
    title: "OnePlus 11",
    type: "Phone",
    serialNumber: "OP-11",
    isNew: false,
    photo: "",
    specification: "256GB, Green",
    guaranteeStart: "2023-05-20T00:00:00.000Z",
    guaranteeEnd: "2024-05-20T00:00:00.000Z",
    priceUSD: 800,
    priceUAH: 31000,
    defaultCurrency: "UAH",
    groupName: "Phones",
  },
  {
    title: "Logitech Brio 4K",
    type: "Accessory",
    serialNumber: "LOGI-BRIO",
    isNew: true,
    photo: "",
    specification: "Webcam 4K HDR",
    guaranteeStart: "2023-10-15T00:00:00.000Z",
    guaranteeEnd: "2025-10-15T00:00:00.000Z",
    priceUSD: 200,
    priceUAH: 7500,
    defaultCurrency: "USD",
    groupName: "Accessories",
  },
  {
    title: "Anker USB-C Hub",
    type: "Accessory",
    serialNumber: "ANKER-HUB",
    isNew: true,
    photo: "",
    specification: "7-in-1 USB-C Dock",
    guaranteeStart: "2024-03-01T00:00:00.000Z",
    guaranteeEnd: "2026-03-01T00:00:00.000Z",
    priceUSD: 60,
    priceUAH: 2300,
    defaultCurrency: "UAH",
    groupName: "Accessories",
  },
  {
    title: "Brother HL-L2350DW",
    type: "Printer",
    serialNumber: "BRO-HL2350",
    isNew: true,
    photo: "",
    specification: "Mono Laser, Duplex",
    guaranteeStart: "2024-01-01T00:00:00.000Z",
    guaranteeEnd: "2026-01-01T00:00:00.000Z",
    priceUSD: 160,
    priceUAH: 6100,
    defaultCurrency: "USD",
    groupName: "Printers",
  },
  {
    title: "Epson EcoTank L3250",
    type: "Printer",
    serialNumber: "EP-L3250",
    isNew: false,
    photo: "",
    specification: "Color InkTank, Wi-Fi",
    guaranteeStart: "2022-09-01T00:00:00.000Z",
    guaranteeEnd: "2024-09-01T00:00:00.000Z",
    priceUSD: 240,
    priceUAH: 8800,
    defaultCurrency: "UAH",
    groupName: "Printers",
  },
];
